### ISSUE TITLE
utf-8' codec can't decode byte 0xff in position 0

### ISSUE THREAD

**Issue by cszczepanski** [pmarti/python-messaging#42]
Hello, I try to use python-massaging. I resumed(took back) your example for the encoding of a MMS text + photo, but here is the error message:

pi@raspberrypi:~/PycharmProjects/mms $ python3 mms.py 
Traceback (most recent call last):
  File "mms.py", line 13, in <module>
    payload = mms.encode()
  File "/usr/local/lib/python3.4/dist-packages/python_messaging-0.5.12-py3.4.egg/messaging/mms/message.py", line 223, in encode
  File "/usr/local/lib/python3.4/dist-packages/python_messaging-0.5.12-py3.4.egg/messaging/mms/mms_pdu.py", line 607, in encode
  File "/usr/local/lib/python3.4/dist-packages/python_messaging-0.5.12-py3.4.egg/messaging/mms/mms_pdu.py", line 802, in encode_message_body
  File "/usr/local/lib/python3.4/dist-packages/python_messaging-0.5.12-py3.4.egg/messaging/mms/message.py", line 552, in data
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

You could explain me how to take out there.
Thank you for your help
best regards
christophe

**Comment by cchristian** [comment]
I recently started migrating my codebase from python2 to python3 and encountered same.
